### ISSUE TITLE
example usage

### ISSUE THREAD

**Issue by rubiin** [anchan828/nest-i18n#538]
Can i get a minimal app with the package usage for rest api with nestjs. would be easy to implement

**Comment by rubiin** [comment]
@anchan828

**Comment by anchan828** [comment]
Hi @rubiin, Is README not enough for you?
https://github.com/anchan828/nest-i18n/tree/master/packages/i18next#quick-start

**Comment by anchan828** [comment]
Created example repo
https://github.com/anchan828/nest-i18n-example

**Comment by rubiin** [comment]
Also is there a package for regular translations? I am thinking of using i18next

**Comment by anchan828** [comment]
Sorry for the late reply. I just added basic usage.
https://github.com/anchan828/nest-i18n/commit/3850fb0876de0e3549ef5dbc7a3e187d9c323350

I close this issue. Please create again if you want to ask more questions.
